import PostTodo from '@/components/PostTodo';
import Todos from '@/components/Todos';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>TODO アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-xl mx-auto p-8">
        <h1 className="text-2xl font-bold text-center mb-8">TODO アプリ</h1>
        <div className="space-y-2">
          <PostTodo />
          <Todos />
        </div>
      </main>
    </>
  );
}
